Fix AutoCrafting in Spigot 1.12.2
Back in the ol' days... There were no such thing as `Material.BIRCH_PLANKS`. And that caused a NoSuchMethodError. As simple as that ^^